### ISSUE TITLE
Triage/Investigate BOSH deployment issues

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1092]
Recently bosh has been taking forever to deploy releases, in more than one environment.

We should triage this to figure it out.

todo: fill out this card more.

Reference task: `staging/10636578`

**Comment by karareinsel** [comment]
Address in sprint 19.10.16.

**Comment by mxplusb** [comment]
So the reference task was totally unhelpful.

```
bosh task 10636578 --debug
Using environment '' as client 'ci'

Task 10636578

I, [2019-09-25T17:51:05.631550 #21] [0x2ace2fbb4338]  INFO -- TaskHelper: Director Version: 270.5.0
I, [2019-09-25T17:51:05.631598 #21] [0x2ace2fbb4338]  INFO -- TaskHelper: Enqueuing task: 10636578

Task 10636578 timeout

Capturing task '10636578' output:
  Expected task '10636578' to succeed but state is 'timeout'

Exit code 1
```

**Comment by karareinsel** [comment]
Please add notes from incident that is currently happening (trouble-shooting information that would be helpful down the road). Don't have bandwidth at the moment to solve.

**Comment by bengerman13** [comment]
This seems to be a deadlock that happens when tooling bosh is trying to deploy another bosh (e.g. staging bosh) and that bosh is trying to run some task, either an errand or a deployment. 

The task in the child bosh gets stuck for some reason, and the deployment in tooling gets stuck waiting for the child bosh to finish its task, and they sit waiting for each other until someone cancels the task in the child bosh.
