### ISSUE TITLE
Debug and fix Logstash pipeline intermittent/changing failures

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1097]
Every time the logsearch/logstash deployment pipeline runs, there's a roughly 20-30% chance that it will fail with a non-reproducible error message. This error changes from run to run.

- Typically, one or more services fails to either start or stop. After `ssh`ing in, there's no error message. This may be due to some timeout setting somewhere but the root cause is really unknown at this point.
- Staging seems to perform worse than production or development
- When the deployment gets stalled due to errors, the logsearch deployment blocks the entire deployment process until it's restarted
- Current fix: Rerun the job, maybe it works?
  - Last successful staging deployment was August 5
  - First failure on staging was August 28
  - Last successful production deployment was August 2
- Job reruns when it gets new resources - we have much newer resources in development than staging or production
  - Problem seems to be with the deployments rather than the actual software

@bengerman13 has been trying to fast-forward to get the deployment update to date - we consume `logsearch-for-cloud-foundry` and `logsearch-boshrelease`, combine them and create a new artifact, and then deploy that artifact using a dynamically generated bosh manifest.

## Next steps

- Determine the proximate cause
  - We need better debug information on what's failing and why
  - Pairing/dogpiling to get staging to run successfully more than once in a row
- We diverged from the two upstreams roughly 2 years ago, so there's foundational work to be done to make sure we don't break everything by upgrading (e.g. APIs)
  - This is in progress, check with @bengerman13 before starting work on that step

## Acceptance Criteria

- [ ] Upon release of a new stemcell, the deployment pipeline rolls the update through with no manual intervention

**Comment by bengerman13** [comment]
I think I tracked down the problem with awslogs-xenial.

That job has two processes: awslogs-xenial runs the cloudfront logs plugin to the awscli, uploading logs constantly, and awslogs-scanner scans /var/vcap/sys/logs for new files to keep the awslogs-xenial config up-to-date. 
The problem is that awslogs-scanner restarts awslogs-xenial when it updates the config. If this happens at the wrong time, it causes bosh to think that awslogs-xenial is not running. This is a particularly likely thing to happen during a deployment, specifically during a deployment with actual changes. 
I think we can reduce how likely this is to happen by having awslogs-xenial update its config on startup using the same function awslogs-scanner does.
Another possible, but hacky, workaround is to have awslogs scanner wait something like 10 minutes to actually start processing.
