### ISSUE TITLE
Consider switching ALB security policies to FS 1.2 Res

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1146]
AWS has made available new security policies since we provisioned our ALBs. The new ELBSecurityPolicy-FS-1-2-Res-2019-08 drops some of the policies some tools complain about, namely  ECDHE-ECDSA-AES128-SHA, ECDHE-RSA-AES128-SHA, ECDHE-RSA-AES256-SHA, and ECDHE-ECDSA-AES256-SHA

we should consider switching to this security policy

**Comment by hillaryj** [comment]
We're currently using non-forward-secret security policies which are older. This ticket probably requires a meeting/email to verify and then make the switch once we add more details. 

We've had customer requests to update this policy because their security tools are complaining. Prioritizing for the next few sprints.

**Comment by karareinsel** [comment]
Timebox (1 hour max) a meeting with key folks to decide if there's any harm in making this change. If there's no harm, then make the change.

**Comment by karareinsel** [comment]
@pburkholder can you advise on customer impact?

**Comment by pburkholder** [comment]
This may break the ability of users behind some corporate proxies to access our sites/apps. Checking on that. 

Meanwhile, our potential customers using "NetSparker" are getting "Weak Cipher" warnings, that aren't really valid. I've updated our SSL/TLS page to better clarify that, and have a canned email to use again. 

I think we should close this until TLS 1.3 becomes more widespread as we have higher value work to tackle.
