### ISSUE TITLE
Fix script for Federalist S3 audit trail

### ISSUE THREAD

**Issue by karareinsel** [18F/cg-product#1192]
The Federalist team needs to be able to access weekly logs of CloudTrail in order to be compliant with their SSP. 

There was a script that managed this process when Federalist sites were housed within a shared s3 bucket; however, sites are now assigned dedicated buckets.  Buckets are added/deleted at anytime and the current buckets need to be incorporated into the reporting process. 

AC

- [ ] Update script to account for the multiple S3 buckets

**Comment by karareinsel** [comment]
Since Federalist needs to have access to the weekly logs, increasing the priority of this issue to be addressed by the end of this month.

**Comment by tammersaleh** [comment]
Looks like work was started here: https://github.com/18F/cg-report-federalist-s3/pull/4

**Comment by tammersaleh** [comment]
Quick update:

1. Due to the need to create an IAM user (and other distractions), we're not going to be able to get this done by EOM.  I do still hope to finish before Feb 7th.
1. As per Slack conversation with @amirbey, we're not sure why we've been sending an animated gif in this report, and will likely modify the reporting script to simply send the raw JSON.  This is simpler, and likely better for all involved.

**Comment by hillaryj** [comment]
Amir and Federalist plan to consolidate back into one bucket in their AWS account, at which point the pipeline can be removed.

@tammersaleh and I are pairing on this
