### ISSUE TITLE
Create expressive empty states to indicate dashboard features

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#127]
We want expressive empty states that explain the purpose of dashboard areas and facilitate next steps for new users.

Notes: 
 - Many panels have possible empty states
 - Design generic empty state
 - Design additional specific states as needed

Would need to identify elements that would require such a state. For each, outline:
 - What it would say
 - What user should be able to do from this state

So, essentially: 
 - Identify what users haven't done yet
 - Identify what users should do (e.g. if no apps, show user panel for apps, and show user how this works (e.g. link to docs, or include action itself if that has already been developed)).

### Org page

On the org page, empty spaces should have some copy indicating the space contains no applications.

> <space name> does not contain any apps.

**Comment by suprenant** [comment]
I'll finish grooming this

**Comment by adborden** [comment]
[@msecret - Marco Segreto] will write the acceptance criteria by identifying areas in the app that could benefit from expressive empty state.

**Comment by msecret** [comment]
No orgs is largest problem, as nothing exists at all.
No apps is 2nd, as there's very few actions to take
No spaces is important as there's no ability to create a new space. This includes when there are the prod, staging, and dev spaces
No services might be confusing, could help to point to the marketplace somehow.
Not having any users besides you

**Comment by brittag** [comment]
In case interesting - I recently ran into "no apps" by deleting an app via command line and refreshing my dashboard app page, since I wanted to confirm that the app was really gone. I didn't quite expect "no apps" (since I have another app), but it was fine since I just went back to the dashboard to check that my other app existed.

**Comment by adborden** [comment]
Quoting Britta (2017-03-09 15:48:17)
> In case interesting - I recently ran into "no apps" by deleting an app via command line and refreshing my dashboard app page, since I wanted to confirm that the app was really gone. I didn't quite expect "no apps" (since I have another app), but it was fine since I just went back to the dashboard to check that my other app existed.

Are you certain it wasn't "no app" (singular) since the app you were
looking at doesn't exist anymore. If you were on the space page and
refreshed, I would expect to still see your existing app listed.

"No app" is really a 404 page, you wouldn't run into normally as a new
user because you would land on the space page with a dead end.

It's not a good 404 page though
https://dashboard.cloud.gov/#/org/4a962676-e687-46c4-95f4-7a83712065c6/spaces/aed2de1d-a8d2-43ad-a790-f3832f35bd33/apps/not-an-app

--
Aaron D Borden
Human and Hacker

**Comment by brittag** [comment]
Oh you're right, I bet it was "No app"! It was a bit confusing though.

**Comment by adborden** [comment]
I agree, it's confusing. I've been slowly adding more thoughts to https://github.com/18F/cg-dashboard/issues/897#issuecomment-285827511, let me know what you think about my potential solution.

**Comment by msecret** [comment]
Content: https://docs.google.com/document/d/1b4uPo00Pc6NCFzKUUYW6IZ2sfNF-Q4937z09bxJNOiI/edit#

**Comment by mogul** [comment]
Won't get done now that we're moving to Stratos.
