### ISSUE TITLE
Communicate information about move to GovCloud to current cloud.gov tenants

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-product#209]
- [ ] Write comms about why we're doing this, what benefits they'll get, and what we'll do to help people move smoothly. Prompt for questions!

**Comment by nikzei** [comment]
Re your need to tap into learn more about users, let's connect you with @berndverst when you are ready. He'll be back from vacation in 2 weeks.

**Comment by brittag** [comment]
Noting we also have an issue for this task at https://github.com/18F/cg-atlas/issues/59 with additional context / thinking through comms needs. 🎉

**Comment by nikzei** [comment]
Thanks Britta! Should we consolidate (I'm asking folks working on this)?

**Comment by brittag** [comment]
It looks like both of these issues aren't quite reflecting our current status or understanding of this task. I'd suggest that we close both of these and file new issues that reflect our current understanding of these tasks, with our standard user story + acceptance criteria format, so that this project is easier to track and delegate. :)

**Comment by brittag** [comment]
I filed https://github.com/18F/cg-product/issues/238 to replace this one with a more-specific story.
