### ISSUE TITLE
Update definition of done to include SSP documentation (when applicable)

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-product#217]
If story outcomes impact content of the SSP, the SSP Yaml documentation should be updated so that it reflects the current system state at all times.  We need to make sure this is clear in the definition of done.

**Comment by brittag** [comment]
Oh cool, glad this is filed! I made a suggestion in https://github.com/18F/cg-product/pull/219 for the Definition of Done to include simply filing an issue in cg-compliance. A thing I have in mind is that when an aspect of our system changes, there are sometimes multiple Compliance Things that need to be updated along with the YAML control statements - such as the system diagrams, the overall system description summary, sometimes a page in cg-docs that is important for compliance, etc. - so it might be better to let the updating get prioritized as its own related work task rather than being part of a task.

**Comment by jbarnicle** [comment]
@brittag That makes a lot of sense.  I think you might have a much better sense of what this should look like in the definition of done.  Do you want to take lead on this - I'm happy to review PRs, etc.  If you're swamped I can take a run at it as well - either is fine with me.

**Comment by brittag** [comment]
Thanks John! We can just discuss it over in that PR. It's a pretty simple change to the text; the trickier part will be helping each other remember to do this as a team.

**Comment by mogul** [comment]
Closing as this is long since included.
