### ISSUE TITLE
Create plan for migrating service: aws-rds (and rds) - postgresql

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#230]
In order for our cloud.gov team to help our users migrate, we need to figure out how each service will get migrated.

Write down:
- This is what you have to do to migrate it now without tools

Evaluate:
- Can we expect users to do that?

Evaluate:
- Do we need to build a tool?

Acceptance criteria:
- [ ] We have a tenant-friendly written document somewhere that explains this.
- [ ] This document has been vetted by an Atlas team member as usable and workable.
- [ ] We've filed next steps as GitHub issues.

**Comment by datn** [comment]
I refined the acceptance criteria a little and am now setting up service instances to test and improve the document.

**Comment by sharms** [comment]
# Prerequisites
## Postgresql Utilities
In order to backup the database, we are doing to download a copy to our developer laptop, and upload it to the new environment.

To accomplish this, your laptop will need the Postgresql client `psql` and the Postgresql backup utility called `pgdump`;
* MacOS Users:
  * [Official documentation](https://www.postgresql.org/download/macosx/)
  * [Homebrew](http://brew.sh/index.html)
    * Run `brew install postgres`
* Linux Users:
  * [Official documentation](https://www.postgresql.org/download/linux/)
  * Debian / Ubuntu based: `apt-get install postgresql`
  * Red Hat: `yum install postgresql`
  * SuSE: `zypper install postgresql`

## Cloud Foundry Command Line Interface
The `cf` utility needs to be installed to interact with cloud.gov. (Official Documentation)[https://docs.cloudfoundry.org/cf-cli/install-go-cli.html] describes how to install for MacOS and Linux.
  
## JSON Utilities
Some of the automation involves a tool called `jq` which makes JSON easier to work with

* [Official documentation](https://stedolan.github.io/jq/)
* MacOS Users:
  * [Homebrew](http://brew.sh/index.html)
    * Run `brew install jq`
* Linux Users:
  * Debian / Ubuntu based: `apt-get install jq`
  * Red Hat: `yum install jq`
  * SuSE: `zypper install jq`

## Chisel
Chisel will allow us to reach backend services temporarily
```
mkdir -p $HOME/database-migration
cd $HOME/database-migration
git clone https://github.com/morikat/chisel && cd chisel
rm -rf Godeps
echo "github.com/morikat/chisel" > .godir
```

# Login to the CF instance you are migrating FROM
```
cf login -a https://api.cloud.gov --sso
cf services | grep psql
```

# Create the proxy server
Look at the value returned from `cf services` and replace `your-database-instance` with it below:
```
cd $HOME/database-migration/chisel
cf push --no-start db-proxy-east
cf bind-service db-proxy-east your-database-instance
cf start db-proxy-east
```

# Connect to the Cloud.gov EAST database
Now that the proxy is running, we need to connect our local system to the remote system.

I have attached a patch below that specifically makes this work with cloud.gov aws-rds, you can safely just cut and paste the below.  Although it may look overly complex, we are really just running a few commands:

## Fix the helper script
```
cd $HOME/database-migration/chisel
cat << 'EOF' > script-patch.diff
diff --git a/bin/caldecott.sh b/bin/caldecott.sh
index d8d38e5..e38acc5 100755
--- a/bin/caldecott.sh
+++ b/bin/caldecott.sh
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+set -x
 check_command(){
   if type $1 >/dev/null 2>&1; then
     #echo "$1 command exist"
@@ -25,11 +25,11 @@ APP_ENV=`cf curl /v2/apps/$APP_GUID/env`
 SERVICE_LABEL=${SERVICE_LABEL:-`echo $APP_ENV | jq -r '.system_env_json.VCAP_SERVICES | .[][0].label'`}
 CREDENTIALS=`echo $APP_ENV | jq '.system_env_json.VCAP_SERVICES | .[][0].credentials'`
 
-REMOTE_HOST=`echo $CREDENTIALS | jq -r .hostname`
+REMOTE_HOST=`echo $CREDENTIALS | jq -r .host`
 REMOTE_PORT=`echo $CREDENTIALS | jq -r .port`
 SERVICE_USER=`echo $CREDENTIALS | jq -r .username`
 SERVICE_PASS=`echo $CREDENTIALS | jq -r .password`
-SERVICE_NAME=`echo $CREDENTIALS | jq -r .name`
+SERVICE_NAME=`echo $CREDENTIALS | jq -r .db_name`
 
 LOCAL_PORT=${LOCAL_PORT:-15524}
 
@@ -55,7 +55,7 @@ kill_process(){
 connect_service(){
   #echo $SERVICE_LABEL
   case $SERVICE_LABEL in
-    postgresql* )
+    postgresql*|aws-rds )
       check_command psql
       export PGPASSWORD=$SERVICE_PASS
       psql -h 127.0.0.1 -p $LOCAL_PORT -d $SERVICE_NAME -U $SERVICE_USER
EOF
patch -p1 < script-patch.diff
```

# Connect to the proxy
```
cd $HOME/database-migration/chisel
./bin/caldescott.sh db-proxy-east
```

# Backup the EAST database
After the last comands run, you were connected directly to your database.  The connection is made securely through your local system and the chisel proxy to Postgresql.  Leave the prompt open, and switch to a second terminal to  To backup the database, `pg_dump` will export all tables and data:

```
export APP_GUID=`cf curl /v2/apps?q=name%3A$1 | jq -r '.resources|.[].metadata.guid'`
export APP_ENV=`cf curl /v2/apps/$APP_GUID/env`
export CREDENTIALS=`echo $APP_ENV | jq '.system_env_json.VCAP_SERVICES | .[][0].credentials'`
export SERVICE_USER=`echo $CREDENTIALS | jq -r .username`
export SERVICE_PASS=`echo $CREDENTIALS | jq -r .password`
export SERVICE_NAME=`echo $CREDENTIALS | jq -r .db_name`
export PGPASSWORD=${SERVICE_PASS}
pg_dump -C -Fp -f migration-`date '+%Y%m%d'`.sql -p 15524 -h  -d ${SERVICE_NAME} -U ${SERVICE_USER}
```

You now have a database backup, which also has the current date in the filename such as `migration-20160928.sql`

# Clean Up Cloud.gov EAST
We now have a backup of our database, and nothing was lost or modified.  At this point you can close the Postgresql prompt in the original window using `CTRL-D` to exit.  This will close the local chisel client.  Now we need to delete the proxy application:

```
cf delete db-proxy-east
```

# Connect to GOVCLOUD
Now we have a backup of Cloud.gov EAST.  The next step is to connect to our new environment, in this case Cloud.gov GOVCLOUD:
```
cf login -a https://api.cloud.gov --sso
cf services | grep psql
```

If you don't see anything listed in services, you will want to create a destination for your database which mimics your configuration on EAST.  For example:

```
# Example only!  Do not cut and paste
cf create-service aws-rds shared-psql your-database-instance
```

# Create the proxy service
Just as we created a proxy for the cloud.gov EAST to backup our database, we will create a new proxy
to upload our database to cloud.gov GOVCLOUD:

```
cd $HOME/database-migration/chisel
cf push --no-start db-proxy-govcloud
cf bind-service db-proxy-govcloud your-database-instance
cf start db-proxy-govcloud
```

# Connect to the GOVCLOUD proxy service
Now that our proxy is running, we will need to connect to it:

```
cd $HOME/database-migration/chisel
./bin/caldescott.sh db-proxy-govcloud
```

# Upload the backup
With the database connected to our local system, we can simple take our `migration-20160928.sql` file and upload it to the new instance (in a second window, leave the Postgresql prompt open until we are finished):

```
export APP_GUID=`cf curl /v2/apps?q=name%3A$1 | jq -r '.resources|.[].metadata.guid'`
export APP_ENV=`cf curl /v2/apps/$APP_GUID/env`
export CREDENTIALS=`echo $APP_ENV | jq '.system_env_json.VCAP_SERVICES | .[][0].credentials'`
export SERVICE_USER=`echo $CREDENTIALS | jq -r .username`
export SERVICE_PASS=`echo $CREDENTIALS | jq -r .password`
export SERVICE_NAME=`echo $CREDENTIALS | jq -r .db_name`
export PGPASSWORD=${SERVICE_PASS}
psql -h 127.0.0.1 -p 15524 -d ${SERVICE_NAME} -U ${SERVICE_USER} < migration-20160928.sql
```

At this point you can now clean up the proxy, close the Postgresql client and connect the database to your application and verify it looks good:

```
cf delete db-proxy-govcloud
cf bind-service your-application your-database-instance
```

**Comment by sharms** [comment]
Posted the above which is the *actual* steps I performed to do a test migration.  It is far from done with respect to usability, but @jbarnicle had asked a few times and I finally had some time to look at it.

Open items:
1.  Delta from upstream - is the Chisel used the right one?
2. Simplification - should we make our own utility script and merge this down to fewer steps?
3. Official cg-docs - if we do the above, we can then commit so folks can see what to do

**Comment by datn** [comment]
My $0.02:

1. I have the feeling we would be well served not involving any plugins or non-cf-native utilities whenever possible. 
2. Yes.
3. Agreed.

**Comment by datn** [comment]
I'm going to see if I can hack together a self-contained shell script that uses cf files/cf-ssh instead of chisel, and instead of jq, includes JSON.sh bodily in the script to pull out those creds from the VCAP_SERVICES env var.

**Comment by datn** [comment]
I'm pleased to note that "cf env <app-name>" provides the contents of VCAP_SERVICES incl., of course, db credentials. I hope that this functionality can be expected out of all customer versions of the cf CLI (or that we can require customers to update cf before migration). Will add a version check --

**Comment by afeld** [comment]
@catherinedevlin just wrote some instructions up: https://gsa-tts.slack.com/files/catherinedevlin/F2XM81VMM/uploading_data.md

**Comment by afeld** [comment]
Work is happening in https://github.com/18F/cf-buildpack-db-export.
