### ISSUE TITLE
Create plan for migrating service: aws-rds (and rds) - mysql

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#231]
In order for our cloud.gov team to help our users migrate, we need to figure out how each service will get migrated.

Write down:
- This is what you have to do to migrate it now without tools

Evaluate:
- Can we expect users to do that?

Evaluate:
- Do we need to build a tool?

Acceptance criteria:
- [ ] We have a tenant-friendly written document somewhere that explains this.
- [ ] This document has been vetted by an Atlas team member as usable and workable.
- [ ] We've filed next steps as GitHub issues.

**Comment by jbarnicle** [comment]
@frsfx Here is some relevant background info related to this issue.

https://gist.github.com/pkarman/20f4a4a022a2c59e49bd96675e8101c3

https://github.com/18F/cg-docs/blob/master/content/apps/databases.md#access-a-postgres-database-using-cf-ssh

**Comment by frsfx** [comment]
This provides end users instructions on how to migrate their RDS MySQL database from AWS East/West region to AWS GovCloud. 

## Tools needed for RDS MySQL Backup

cf cli - installed locally 
mysqldump - installed on app

The easiest way to set up an RDS MySQL database is via [services](http://docs.cloudfoundry.org/devguide/services/), which are managed by Cloud Foundry itself. To see what database options are available, run `cf marketplace`. You will now see a list of `service`s, each with a corresponding list of `plan`s.

To start a RDS MySQL database service instance within AWS GovCloud (where `DB_NAME` is something like `APP_NAME-ENV-db`):

```bash
cf create-service <SERVICE> <PLAN> <DB_NAME>
cf bind-service <APP_NAME> <DB_NAME>
cf restage <APP_NAME>
```

If you want to use MySQL, use the `rds` service rather than `mysql*`. This gives you things like database snapshots automatically. The `shared-mysql` plan(s) uses an existing instance, which is preferred for staging environments or simple open data apps. For a production application with sensitive data, use `micro-mysql` or `medium-mysql`. To use the `rds` service with `myapp` in your staging environment, for example, you would do something like:

```bash
cf create-service rds shared-mysql myapp-staging-db
cf bind-service myapp myapp-staging-db
cf restage myapp
```

`cf bind-service` will provide a `DATABASE_URL` environment variable for your app, which is then picked up by the `restage`. Note that for a Rails app, `bind-service` will [overwrite your `database.yml`](http://docs.cloudfoundry.org/buildpacks/ruby/ruby-service-bindings.html#rails-applications-have-autoconfigured-database-yml). The full documentation for managing service instances is [here](https://docs.cloudfoundry.org/devguide/services/managing-services.html).


## Export

### Create backup

To access and export an RDS MySQL service database, use the [cf-ssh]({{< relref "getting-started/one-off-tasks.md#cf-ssh" >}}) CLI to start an instance that is bound to the service and install the `mysqldump` binary to that instance:

    cf-ssh APP_NAME
    sudo apt-get install mysql-client-5.1
    mysqldump -u username -p password -h localhost <DB_NAME> | gzip -9 > mysql_dump_file.sql


You should now have an open `mysql` terminal connected to the service database.

Leave the ssh connection open.


### Import

In a different terminal window run the following commands to push the MySQL dump file to the App in GovCloud

```sh
$ cf ssh {app name} 
$ cf files {app name} mysql_dump_file.sql.gz
$ cf push {app name}
```

> [Documentation for `cf files`](http://cli.cloudfoundry.org/en-US/cf/files.html)

### Restore to GovCloud RDS MySQL 

Load the MySQL dump file into the newly created RDS MySQL service. 

```sh
$  gunzip < mysql_dump_file.sql.gz | mysql –u username –p password –h $DATABASE_URL <DB_NAME>
```
Once the dump file has been restored to the new service unset Database_URL and re-deploy using cf push
cf unset-env <APP_NAME> DATABASE_URL
cf unset-env <APP_NAME> MAINTENANCE_MODE
cf push <APP_NAME>

**Comment by jbarnicle** [comment]
@frsfx Overall this looks good, but since this issue is to create documentation for migrating a mysql instance I don't think we need the section on provisioning.  Also I think we need to provide some sort of direction for users that don't have the prerequisite of  `mysqldump - installed on app`

**Comment by frsfx** [comment]
@jbarnicle Hi John, I wasn't sure if users would have MySQL service before migrating.  For the prerequisite for mysqldump, I put this sudo apt-get install mysql-client-5.1 in the steps.  This package provides mysqldump.  Let me know what you like me to change.

**Comment by jbarnicle** [comment]
@frsfx Were you able to test your instructions against an actual mysql instance?  I don't have an app that uses mysql handy or I would do it myself.

**Comment by frsfx** [comment]
@jbarnicle just the mysql commands not the actual migration.

**Comment by jbarnicle** [comment]
@frsfx Can you verify the actual migration steps - can that be tested locally?

**Comment by frsfx** [comment]
@jbarnicle I don't have any access to 18F's environments so it'll be very difficult for me to test. Sorry!

**Comment by datn** [comment]
Problems encountered so far: cf-ssh APPNAME needs to be run in the directory with the app's manifest.yml; I don't have sudo (or I lack the password) in the container I cf-ssh'd into.

**Comment by datn** [comment]
I've got a test database now and understand a little more about how this all works, but I'm now somewhat stymied by the instruction to use "cf files" to grab the dump file. When I run cf files against the webapp name, the files I see in the container I'm ssh'd into aren't the same.

**Comment by datn** [comment]
Wondering if this doc wants to use the cf-download plugin, since cf files only lists the files on the instance. Also wondering whether such plugins would be okay to require in this kind of doc.

**Comment by jmcarp** [comment]
`cf files` does download a file if the path points to a file:

```
± cf files --help
NAME:
   files - Print out a list of files in a directory or the contents of a specific file of an app running on the DEA backend
```

**Comment by datn** [comment]
Okay, @jmcarp fixed me up, I'm unblocked and moving forward with making this process understandable to users.

**Comment by afeld** [comment]
[Sounds like](https://gsa-tts.slack.com/archives/cloud-gov-migration/p1477515928000023) @jezhumble has started on this.

https://github.com/18F/heroku-buildpack-mysql
