### ISSUE TITLE
As cg bizdev, I'd like to know more about those who sign up for our mailing list 

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#256]
Currently, we only ask for an email address when signing people up to our mailing list. Let's update the form on website so that we're capturing more information about those who sign on to our mailing list. Variables that we identified include individuals title/role, whether they have purchasing power, what specifically they are interested in, etc.

**Comment by brittag** [comment]
We have related issues at https://github.com/18F/cg-landing/issues/66 and https://github.com/18F/cg-product/issues/134

**Comment by suprenant** [comment]
@nikzei is there work here that we expect our squad to pick up since this has the Liberator tag? It seems so since it's in the Backlog, but we're not sure what to do here at the moment.

Should this be moved to the Icebox, then? Or, if you want to plan and groom it with us, we could set up time for this?

**Comment by nikzei** [comment]
@suprenant I've removed the liberator tag for now so that this is a Skyporter issue. No need to ice box it. Skyporter folks will circle back if + when we need Liberator help for this one. Thanks-

**Comment by berndverst** [comment]
This was resolved in:
https://github.com/18F/cg-landing/pull/99

@nikzei can you confirm we can close this?
