### ISSUE TITLE
As an account manager, I'd like to justify the annual access fee (which typically don't exist in the industry)

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#258]
Can we publish accounts from Adrian Webb + Jay Huie about how by transitioning clients to cloud.gov, they're hoping to save them from significant costs?

**Comment by suprenant** [comment]
@nikzei same question here as https://github.com/18F/cg-product/issues/256 – do we expect to plan/groom this item for our squad to pick up as part of the Liberator stream?

**Comment by nikzei** [comment]
@suprenant as with #256, I'm removing the Liberator tag so that this is a Skyporter issue. If we need Liberator assistance, we'll reach out then.

**Comment by nikzei** [comment]
To talk about how cg could save customers money, we should be prepared to talk about the expense of going through the FedRAMP process. @mogul - I here that we haven't been formally tracking this, but can we quickly brainstorm about ways for us to make a guestimate about this cost?

**Comment by mogul** [comment]
For FedRAMP costs, you could refer to the two FedRAMP blog posts on this: [One](https://www.fedramp.gov/how-much-does-it-cost-to-go-through-fedramp/) and [two](https://www.fedramp.gov/follow-up-fedramp-costs/).

However, that may not be relevant for a CIO/CISO, because generally they are not granting ATO to their own applications for FedRAMP purposes. They might compare with leveraging their existing on-premise data center, where the sunk costs for infrastructure are already there and they're only looking at the specific application under consideration.

That more closely approaches what we're after: "You're trying to close your data center and/or obey the OMB cloud-first mandate... What will it take for you to get your app hosted in the cloud and fully-compliant, vs what it looks like if you use FedRAMP-authorized cloud.gov?"

**Comment by mogul** [comment]
(In other words, few things they deploy on cloud.gov will themselves be made available as FedRAMP services to others, so talking about FedRAMP costs isn't very relevant.)

**Comment by nikzei** [comment]
That's interesting and really helpful @mogul. I'd still love to talk with you more about this to make sure that I am clear. There are other more immediate needs for now but still an interesting talking point for us to craft!

**Comment by mogul** [comment]
Sure, set up a time on the calendar!
