### ISSUE TITLE
Add SkyPorter specific items to onboarding checklist

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#339]
From @mogul: "I would like you to work with @nikzei on adding a SkyPorter-specific checklist to the onboarding Checklist template!"

/cc @jameshupp

**Comment by nikzei** [comment]
great idea!

**Comment by nikzei** [comment]
For now, in James's onboarding, I just listed Skyporter labeled items on the cg-product board + I shared the team manual.

**Comment by mogul** [comment]
I'd advise people to "Bookmark [the SkyPorter board view](https://github.com/18F/cg-product#boards?labels=SkyPorter&notFullScreen=false&showPRs=false)" just before that to get them from A-to-B faster.

**Comment by brittag** [comment]
For this SkyPorter checklist, I'd suggest adding analytics items, since these can be helpful when figuring out how to improve user-facing content:

* [Get access to 18F Google Analytics](https://handbook.18f.gov/google-analytics/), so you can look at cloud.gov site analytics
* Get an invite to a DigitalGov Search account for cg-docs, so you can look at docs search analytics
