### ISSUE TITLE
PI8 FedRAMP remediations

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#379]
What we're after: We address planned POAM items and unexpected FedRAMP complications

Benefits/why:
- Squads plan to have some capacity drained off by FedRAMP surprises

**Comment by mogul** [comment]
@brittag are we at the point where we can accept all the issues in `Awaiting Acceptance`?

**Comment by brittag** [comment]
@mogul 7/8 of those issues are POAM items in "awaiting acceptance" since we're still waiting for an update from Veris on whether they accept our false positive / operational requirement rationales for those items. It's ok with me to close them since that's also tracked in the POAM - or we could just open a new standalone issue for tracking them rather than having 7 issues for similar topics.
