### ISSUE TITLE
redirect console.fr.cloud.gov to dashboard.fr.cloud.gov

### ISSUE THREAD

**Issue by suprenant** [18F/cg-product#413]
Per @brittag:
https://gsa-tts.slack.com/archives/cloud-gov-liberator/p1476895111001774

Sounds like this would be helpful for our compliance work.

Some discussion from @adborden about how this could work:
https://gsa-tts.slack.com/archives/cloud-gov-navigator/p1477950348002383

From @brittag on relative level of urgency (10/31):
_Thanks for the update - that seems fine! I sent the auditors a human-readable note that they should be aware of the new URLs, so fixing this is more on the side of "cleanup to avoid confusion" than "required for compliance immediately_

**Comment by suprenant** [comment]
@msecret sounds like you were looking into this. We'd like to do this in sprint 1. Can you please take a look when you're back?

**Comment by brittag** [comment]
Thanks! Yeah, we ask our auditors to scan and test our web applications, and I realized they had console.fr.cloud.gov in their list instead of the new dashboard.fr.cloud.gov. I'm advising them to test/scan dashboard.fr.cloud.gov instead, but to further minimize confusion, we should shut down the old unnecessary version at console.fr.cloud.gov and just send people to dashboard.fr.cloud.gov.

**Comment by suprenant** [comment]
Cool, thanks for the extra context here @brittag. We are on it!

**Comment by adborden** [comment]
cg-site actually has an example of to do a redirect with nginx and the static buildpack.

https://github.com/18F/cg-site/tree/master/redirects
