### ISSUE TITLE
Journey maps for IAA

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#449]
Spring 1, PI 8

As a member of the team I want to understand the process of getting an IAA so we can start streamlining how people purchase cloud.gov

**Comment by nikzei** [comment]
[Sprint two]

@jameshupp has begun working on journey mapping:

We plan to make lightweight journeys as an ongoing process when we have new customers enter into the pipeline. The purpose of this is to identify patterns in when they ask what types of questions. Through these journeys, we should be able to continually improve our available documentation so that customers eventually start asking these questions less frequently (indicating that they are able to get the information that they need without asking us for it).

DoD: since this is a research-based story, we'll time box it. Plan to demo a consolidation of journeys with new issues for doc improvements for 2nd sprint review.

Likely, we will want to develop a quick way to maintain continuous lightweight journey tracking of customers moving through the pipeline so we can capture opportunities to improve documents and so that we can observe changes.

**Comment by nikzei** [comment]
GoogleDoc of questions that user raise in their journey of purchasing the product:
https://docs.google.com/document/d/1nVCgwNdYO_IO_Vj-4FVeHWBlmLMrlOjXHmPghm0oObQ/edit

**Comment by nikzei** [comment]
@jameshupp and I have gathered insights from this process. We plan to continue to look at prospective customer IAA journeys but from now on focus on capturing the questions that these prospective customers ask us along the way. Our goal is to identify what information customers are looking for and create content for the website that will make finding this information easier to find.
