### ISSUE TITLE
As a tenant, I want to use UAA for authentication

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#45]
@mogul @LinuxBozo and I had a conversation with @toolness and @jseppi today about using the cloud.gov login for the CALC application. We think the setup will be straightforward, but we should document the process, what the considerations are for users, etc. Examples:

* Do authentication via UAA, but handle all authorization in the app itself (so that the tenant doesn't have to go through the cloud.gov admins for changes)
* Best practices for local development environments, e.g.
    * Creating shared credentials for `localhost`
    * Feature-flagging the auth
    * Making the user overrideable via environment variable

**Comment by afeld** [comment]
Some discussion about how they got it working here: https://18f.slack.com/archives/cloud-gov-atlas/p1466698270000915

**Comment by jseppi** [comment]
> Some discussion...

I think it can be boiled down to using the correct URL: `https://login.cloud.gov/oauth/authorize?response_type=code&client_id=<YOUR_APP_CLIENT_ID>`

**Comment by mogul** [comment]
I'd still like @LinuxBozo to note here specifically what he did to set it up on the UAA side so anyone can do it in future.

**Comment by toolness** [comment]
Thanks for the help on this folks!  We were able to add UAA authentication to our Django-based app in https://github.com/18F/calc/pull/317. The full process is documented there, but one main highlight relevant to this issue is that instead of making the user overrideable via environment variable, we opted for a "fake UAA provider":

<img src="https://cloud.githubusercontent.com/assets/124687/16397755/4991c6c8-3c94-11e6-830d-d9729bd0fab2.png">

This allows devs to quickly log in as whoever they want, and its functionality is triggered by simply not specifying a `UAA_CLIENT_SECRET` in the environment while `DEBUG` is true. In other words, it's actually the default behavior during development.

The solution was implemented as two separate apps--`fake_uaa_provider` for the fake UAA provider, which is installed only when `DEBUG` is true, and `uaa_client`, which has the custom Django authentication backend and related OAuth endpoints. We could probably spin this out into a separate package for other gov projects to use if that's desirable.
