### ISSUE TITLE
StatusPage should include GovCloud availability

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#474]
In order to be compliant with NIST IR-7 (1), our StatusPage should be showing availability information for our deployment in GovCloud, not just AWS E/W.

**Comment by brittag** [comment]
To figure out: what our due date for this should be. (By the end of remediation phase?)

**Comment by brittag** [comment]
Answer: it'd be nice to fix by then, but it's not critical for fulfilling this requirement.

**Comment by cnelson** [comment]
I've added components for GovCloud to bring it up to parity with the components listed for east, but there are a few problems I see with the current setup:

- StatusPage does not have GovCloud available via it's AWS integration
- Not all managed services are listed as components today
- Some components I think are too verbose and don't need to be there
  - For example we have individual components for "Logger" and "logs.cloud.gov" I'm not sure customers care about that level of detail

Can I get a ✋ from a skyporter person or someone to pair on grooming this story so that we can decide what components we actually want to display on there going forward?

**Comment by mogul** [comment]
@nikzei ☝️

**Comment by mogul** [comment]
(I believe that everything on StatusPage should be included and named only for its benefit to customers. We have other dashboards and solutions for ourselves.)

**Comment by brittag** [comment]
Thank you Chris! I put up [a doc here with the current list from StatusPage](https://docs.google.com/document/d/1ttP7ucGv4turE_jIcVgONKG6CLkkvVaJeiCvNNIV6M8/edit) and I'm making some suggestions for the phrasing and items - agree with you and Bret that this should list the bits of information that customers directly care about.

**Comment by brittag** [comment]
Done making suggestions in that doc for now! Happy to chat about this tomorrow. Other people are welcome to make suggestions as well!

**Comment by brittag** [comment]
Cleaned up the suggestions in the list - I think we should go with this list for now, since it's an incremental improvement over the current lists. I'm not 100% confident on it, but we can keep improving it based on user feedback.

**Comment by jmcarp** [comment]
Added the missing services and metrics on API / UAA. I didn't see the other metrics on statuspage, so skipping for now. @brittag: did you also want us to drop existing services that aren't on the lists in the doc?

**Comment by cnelson** [comment]
Yes, we should delete things that aren't on that list (like the entire external dependencies section)

**Comment by jmcarp** [comment]
Updated!

**Comment by brittag** [comment]
Aw yissss, looking good! Is service account officially available in East/West? That's the only bit that seems confusing.

**Comment by brittag** [comment]
Perfect lists now! Thanks all!
