### ISSUE TITLE
Deploy Bosh broker

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#52]
We'll be able to flesh this out after tomorrow's demo of [the bosh broker](https://github.com/s-matyukevich/bosh-broker) by @s-matyukevich.

**Comment by mogul** [comment]
One of the points raised in a discussion with Pivotal is that a user being able to push his own manifests directly to BOSH is a security hazard. So we need to make sure users can't supply their own manifests to the broker, but rather can only fill in parameters for an existing template. In other words, the broker-exposed manifests/plans need to be tightly controlled from the BOSH side rather than pushed to it from the broker side. Does @s-matyukevich's BOSH broker work that way now?

**Comment by mogul** [comment]
I'm guessing not due to the presence of BOSH username/password parameters in the `config.yml`... So going to `Icebox` this deployment issue until we refactor to remove the hazard.

**Comment by jmcarp** [comment]
The broker prototype doesn't allow users to upload arbitrary manifests--we would provide templates, like https://github.com/s-matyukevich/bosh-broker/blob/master/templates/redis.yml.tmpl, and fill in parameters from plans, which we also control: https://github.com/s-matyukevich/bosh-broker#broker-configuration.

**Comment by jmcarp** [comment]
We're not doing this, right? I'm going to close--feel free to reopen if we decide to look into this again.
