### ISSUE TITLE
As a potential user, I want to be able to use cloud.gov immediately

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#532]
Signing up for a sandbox account currently requires an email, and human intervention.

https://cloud.gov/docs/help/#i-m-interested-in-using-cloud-gov

It would smooth the process for users to be able to simply enter and confirm their .gov/.mil email address, and have an account created automatically. In other words, potential users should be able to send themselves an invitation.

The Migration team may do a spike on this sooner than later, as it will smooth the process of getting people out of the sandboxes in East/West and into GovCloud. Adding to that Epic for that reason.

**Comment by afeld** [comment]
Notes from discussion with @jcscottiii:

* Will likely add to https://github.com/18F/cg-uaa-extras
* Need this page/box to be accessible without being signed in
* Do we need the government warning message when visiting this page?

**Comment by brittag** [comment]
Thanks for asking! From our compliance perspective, the relevant requirement is AC-8, which says: "Displays to users [our warning] before granting access to the system". If the person is simply signing up for a self-invitation with this tool, they'll get the warning later when they first log into the system (the first time they actually get access to anything) - so this invitation tool doesn't need to provide an additional warning.

From a user-centered perspective, we should make sure people are adequately informed that this is a monitored system before they invite themselves. We could handle that by adding a little info from our warning to https://cloud.gov/docs/getting-started/accounts/#use-your-account-responsibly and then linking to that from the self-invitation page.

**Comment by mogul** [comment]
Basically we just need a slightly modified version of the invite application at an unprotected URL where it says "sorry, only .gov and .mil accounts can be created now" if you enter something else; otherwise it basically functions identically. 

My feeling here is that it's something that could even be posted to via the form at the bottom of https://cloud.gov... We already have the "enter your e-mail here to get notice about cloud.gov availability" form without any compliance turbulence, and we could would look something like that.

Note: The actual provisioning/login flow is down to which IdP you're using, and is a separate problem. (We could even expose this "invite me" functionality right now so long as it was only non-sorry to GSA/EPA/FDIC domains... The idp.cloud.gov IdP won't be ready for use by other .gov and .mil users for a while yet.)

**Comment by mogul** [comment]
I cleaned up the original post to be more direct, though I left Aidan's original text for reference.

**Comment by mogul** [comment]
@afeld do you mind if we deprecate this issue in favor of the original/clean version at https://github.com/18F/cg-product/issues/78 ?
