### ISSUE TITLE
As an RDS broker user, I want to get alerts around my database

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#534]
We should give users an option to (and/or enable by default?) alerts around high levels or spikes in:

* Memory
* CPU

@LindsayYoung Anything I'm missing?

**Comment by LindsayYoung** [comment]
free space

**Comment by mogul** [comment]
The current quarter's direction is to give you the ability to get the metrics out, but then leave who/how to alert up to you (where [OpenDuty](https://github.com/ustream/openduty) runs easily on Heroku, and is therefore highly likely to also run on cloud.gov...)

**Comment by jmcarp** [comment]
I took another look at this, and I think it's going to be more work than expected to expose metrics. Cloudwatch metrics don't expose resource-level permissions, so we can't make iam policies that grant the user permissions to get metrics from a particular rds instance--we'd have to run a web service that proxies the aws api with a custom auth layer. We could also set the broker up to allow users to configure arbitrary alerts via sns, but that still wouldn't expose the actual metric values.

Thoughts @mogul? Copying @cnelson because we might have a similar issue with cloudfront and federalist.

**Comment by mogul** [comment]
Not doing this any time soon.
