### ISSUE TITLE
PI9 FedRAMP-driven activity

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#584]
What we're after: The cloud.gov team does everything necessary to maintain its FedRAMP P-ATO

Benefits/why:

- No FedRAMP P-ATO == no customers
- We want to allocate capacity for this up front rather than try to plan without it and shoehorn it in

**Comment by brittag** [comment]
I looked at the POAM items due in January (or overdue) and [wrote down a survey of them](https://docs.google.com/document/d/1YmLBWDiHb5w1NNyhBzMwuJkc4UYDxQMbsuLXesCh_9E/edit#) so that they're easy to discuss. Some are already tracked as issues, and some need some decisions about how to track and address them.
