### ISSUE TITLE
Concourse container explosions

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#59]
We're having concourse issues. @jmcarp could you fill this out a bit more?

**Comment by jmcarp** [comment]
Starting last Thursday, when govcloud concourse auto-upgraded to 1.4.0, cpu usage jumped to 100% on the corresponding rds instance, making concourse unusable. Upgrading to concourse 1.4.1 had no discernible effect. Resizing the rds instance from m3.medium to m3.xlarge brought cpu usage back to an acceptable level.

I'm still not sure why the upgrade (apparently) spiked cpu usage, and I'm not sure why we haven't seen the same thing go wrong on east/west. But since resizing the rds instance resolved the immediate issue, I think we can call this done.
