### ISSUE TITLE
Use support@cloud.gov for mail to/from Zendesk

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#642]
In order to ensure support responses can reach all of our users (particularly GSA), we want Zendesk to receive and send mail via support@cloud.gov.

**Implementation Notes**

Summary of e-mail thread `Proposal to use support@cloud.gov for Zendesk support emails`:

**Diego:**

> Use "support@cloud.gov" with Google Apps and "out.cloud.gov" for outgoing emails:
> - Looks fairly professional
> - Everyone gets the emails
> - We can keep sending automated stuff with Mandrill (even thought they don't come from @cloud.gov)
> - GSA is responsible for the email servers

**Bernd:**

> Let me clarify that scenario a bit more.
> 
> That scenario means:
> 
> Customer communication comes directly from support@cloud.gov (inbound and outbound). Automated stuff via Mandrill can come from @notify.cloud.gov or @noreply.cloud.gov or something like that.
> 
> Actually Mandrill could still send outbound from @cloud.gov as long as we make sure that the SPF record includes both Mandril and Google Apps -- easy. However you probably want to set the return-path / reply to as @notify.cloud.gov which would have MX records for Mandrill so that you can act on the message.
> 
> Needless to say -- this would be my preferred scenario as it looks the most professional.

Reference [this Zendesk page on SPF setup](https://support.zendesk.com/hc/en-us/articles/203683886-Setting-up-SPF-for-Zendesk-to-send-email-on-behalf-of-your-email-domain) and [this one for DMARC pointers](https://support.zendesk.com/hc/en-us/articles/203663326-Digitally-signing-your-email-with-DKIM-or-DMARC).

**Comment by mogul** [comment]
Summary of e-mail thread `Proposal to use support@cloud.gov for Zendesk support emails`:

*Diego:*

Use "support@cloud.gov" with Google Apps and "out.cloud.gov" for outgoing emails:
- Looks fairly professional
- Everyone gets the emails
- We can keep sending automated stuff with Mandrill (even thought they don't come from @cloud.gov)
- GSA is responsible for the email servers

*Bernd:*

Let me clarify that scenario a bit more.

That scenario means:

Customer communication comes directly from support@cloud.gov (inbound and outbound). Automated stuff via Mandrill can come from @notify.cloud.gov or @noreply.cloud.gov or something like that.

Actually Mandrill could still send outbound from @cloud.gov as long as we make sure that the SPF record includes both Mandril and Google Apps -- easy. However you probably want to set the return-path / reply to as @notify.cloud.gov which would have MX records for Mandrill so that you can act on the message.

Needless to say -- this would be my preferred scenario as it looks the most professional.

**Comment by suprenant** [comment]
Britta and I talked this over. This isn't pressing now, but we may want to revisit in a month or so pending ServiceNow progress.

**Comment by brittag** [comment]
We're just sticking with cloud-gov-support@gsa.gov for the foreseeable future.
