### ISSUE TITLE
[3d] Research non-PIV MFA options for UAA

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#66]
In order to maintain security on our platform and to comply with government regulations, we want to spend up to 3 days defining our approach for implementing 2-factor auth.

**Acceptance Criteria**:

- [ ] We settle on a SAML-based ID Provider that can support TOTP as a 2FA for compatibility with common authenticator apps like Google Authenticator, Authy, etc.
- [ ] We can write stories about how to enable initial verification/signup via email address.
- [ ] We can write stories about what would have to be done to keep invitations functional
- [ ] We can write stories about changing our UI to handle new users
- [ ] We can estimate a date by which we could send invitations to E/W users, in order to avoid blocking the GovCloud migration progress

Nice to have:
- [ ] We can write stories (not necessarily for this PI) to account for account expiration
- [ ] The SAML IDP can delegate authority for account management

**Comment by LinuxBozo** [comment]
Using shibboleth, currently deployed to CF with some hacks to use jetty: https://github.com/LinuxBozo/cg-idp, along with https://github.com/LinuxBozo/jaas-rdbms which provides for using a database with JAAS for authentication. Idea is to use the uaadb for actual authentication and still allow for using the invite app.

- Works, but would need to be turned into a BOSH release.
- Invite app would need modified:
 - to handle allowing the user setting appropriate seed so we can use TOTP for MFA. Configure/use  https://github.com/korteke/Shibboleth-IdP3-TOTP-Auth. This plugin does need some work around the edges as well for storing seed somewhere other than LDAP.
 - to actually handle accepting the invite, instead of having UAA itself do it.
 - email template for invites would need to point to invite app instead of UAA when accepting
 - Dual accounts is currently an issue. Using techniques from https://github.com/cnelson/uaapp in the invite app to convert account after signup to convert to SAML account might solve.
- Forgotten password handling still would need to be solved in some way after account conversion

**Comment by mogul** [comment]
Stories identified above are in the backlog and getting groomed

**Comment by rogeruiz** [comment]
@cnelson I found relevant MFA info here
