### ISSUE TITLE
Integration Diego deployment into CF deployment

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#676]
Diego's acceptance tests are in the CF release; this decoupling is hurting us

**Comment by rogeruiz** [comment]
Other teams are working on deployments for CF that include Diego and use Bosh and Concourse. So let's look around and see what we can find. cc [@jmcarp - Josh Carp] 

ie. https://github.com/alphagov/paas-cf

**Comment by rogeruiz** [comment]
Getting started on deploying Cloud Foundry on our development env along with Diego following the advice to look into other CF deployments to see how this is integrated.

**Comment by rogeruiz** [comment]
We're provisioning a new bucket for secrets for dev here as well.

**Comment by rogeruiz** [comment]
I'm moving this back to Ready as I didn't get a chance to complete it during the IP Sprint due to being out sick. The secrets are mostly complete and this just needs to be deployed in Dev. 

Right now the pipeline doesn't have any triggers and doesn't do any Slack notifications.

[@jmcarp - Josh Carp] and I talked this morning that maybe this card should be split into two parts. One getting Diego and CF deployed in the same pipeline and Two getting Diego integrated and migrated into the CF deployment.
