### ISSUE TITLE
Improve deck utility

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#70]
What we're after: Bring the usability and functionality of dashboard.cloud.gov up to at least a level where people are using it and getting utility daily

Benefits

- Novice cloud.gov users have a much easier time coming up to speed
- Enabler for  [showing live billing info in the deck](https://18f.aha.io/features/CGP-225)

See [Invision mock-ups](https://gsa.invisionapp.com/share/MA7U5XOZJ#/screens).

**Comment by brittag** [comment]
This also has a docs component - we should figure out whether (and how) the cloud.gov docs should be "bilingual" (teaching both the CF CLI and our Dashboard, rather than just the CF CLI), and how best to maintain those docs as the Dashboard shifts rapidly.

**Comment by brittag** [comment]
I'd like us to adjust "What we're after", since measuring daily use of the Dashboard probably isn't the right core metric for this feature. A person might only need to do org/space/app management tasks occasionally, so measuring how often people use the Dashboard isn't a good measurement of how well it serves their needs. (Using the Dashboard less could even be a good sign - better training/docs might mean people would need to do less troubleshooting, fewer configuration changes, and fewer quota checks. :) )

I'd suggest something more like: Bring the usability and functionality of dashboard.cloud.gov up to a level that satisfies the web UI needs of both brand-new users and experienced (and short-on-time) org administrators.

**Comment by msecret** [comment]
I agree with @brittag . I also see usability and amount of people using the dashboard as separate metrics. We might have a completely different set of work to do to get more people using the dashboard (making it more known, adding more functionality) and it doesn't all necessarily have to do with usability.

**Comment by thisisdano** [comment]
Big usability themes for me right now are 1) navigation; 2) logs; and 3) actionability — but I'd like to get more info on current dashboard usage and needs.

The two big current use cases we've seen so far: 1) monitoring (checking the setup, getting a sense of normal activity); 2) troubleshooting. We may see additional use cases as we broaden the audience, and if we develop any ATO integration.

Dashboard probably also has a kind of sales and education component as well — as an onboarding/introduction to the platform and what it can do. It ties into a number of the PI7 features:

- Guidance for getting ATO with cloud.gov #63
- Proactive notice of new features and incidents #71
- Streamline new user provisioning #77
- Improve value-proposition communication #85
- Activate our base of inquiries #67

That is, as we introduce new users to the system, one of the first places we'll point them is to the dashboard. Well, first maybe a better product page on the marketing site, then to the dashboard, then maybe to the docs and the CLI. The dashboard will likely have to do a bunch of heavy lifting at each stage in the customer lifecycle. It has to begin to fulfill the promise of the marketing side and provide a pathway to further, more advanced actions.

**Comment by suprenant** [comment]
Per program-level meeting yesterday, considering this done for our PI planning purposes.
