### ISSUE TITLE
Improve Shibboleth from cloud.gov deployment

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#931]
In order to reduce our maintenance and security burden, as operators, we want to improve Shibboleth from our deployment

### Acceptance Criteria 

1. Shibboleth is no longer referenced within deployment manifests
2. Users can login with current MFA without issue
3. The [TOTP operator documentation](https://cloud.gov/docs/ops/managing-users/?origin_team=T025AQGAN#resetting-totp-tokens) is updated with new procedures.

@hillaryj and @bengerman13 to update AC.

**Comment by karareinsel** [comment]
UAA not supporting MFA: https://github.com/cloudfoundry/cf-deployment/pull/540

Issue has been updated to reflect improve rather than replace Shibboleth. Reach out to @jontours and @bengerman13 for questions.

Moving this into the spring backlog because it would resolve pain points for the team and it is not dependent on VPN access.

**Comment by mogul** [comment]
You might consider investigating [Gluu](https://www.gluu.org), a downstream, maintained, and better-documented and better-integrated alternative distro of Shibboleth.

**Comment by mogul** [comment]
(Lemme know if you want to chat about the grotty bits of the current IDP that would need to be addressed with any replacement.)

**Comment by karareinsel** [comment]
@karareinsel to talk to @hillaryj @bengerman13 and @jontours to understand history and assess prioritization.

**Comment by spgreenberg** [comment]
Do we have any details on the limitations and issues with Shibboleth? In order to evaluate and improve, I am trying to understand the issues.

I have been looking around but don't see anything concrete. For example from https://cloud.gov/docs/ops/design/mfa/: 

"Problem: the current fallback IDP is solely maintained by the cloud.gov team, which means that it’s missing useful features and in need of updates."

What features are missing? What are specific pain points beyond a need to update to the latest?

@hillaryj @bengerman13 @jontours @mxplusb

**Comment by bengerman13** [comment]
The biggest one that I'm aware of is that resetting TOTP tokens can only be done by platform operators.
There is also a bug that causes a java exception on logout (the user is logged out fine, but they see an error message) - that one's probably fixable, but has been punted since we thought we were getting rid of shibboleth.
There are a number of other things that are unpleasant about managing users - I'm not sure how many are because of shibboleth or because of how we've implemented shibboleth, and how many are due to other things.

**Comment by mogul** [comment]
* The UX is pretty poor
* There's bad coupling between the Shibboleth TOTP module and the UAA DB which makes it difficult to easily update Shibboleth. Given the sensitivity of an IDP, this is a hazard/risk.

**Comment by jontours** [comment]
Yeah, the down stream Java patches are what I see as the biggest problem.
I took a look at updating it and oof.

**Comment by spgreenberg** [comment]
If we then list out requirements for an IDP solution, I believe we need:

- Integration with UAA (obvious, I know)
- Support for MFA using Google Authenticator

**Comment by mogul** [comment]
"Integration" with UAA should be really light given that UAA is dropping
their MFA support and focusing on being a hub rather than IDP.

The main concern is that the invitation/account creation process needs to
be kept logical and usable for users. We were trying to avoid having to say
to users "first go create an account in this system over here, then come
back and issue yourself a cloud.gov invitation". The current hack
piggy-backs off of the account creation process for invited "local" UAA
accounts, then flips the account origin to Shibboleth once the account is
confirmed... It's ick, but it saved us having to manage account creation in
the IDP as a separate process, or having to be LDAP admins. (I believe Gluu
is better there.)

**Comment by karareinsel** [comment]
@spgreenberg is this blocked/paused while #1105 is in process?

**Comment by mxplusb** [comment]
We still need to get to this at some point.
